const plugin = require("tailwindcss/plugin");
const colors = require("tailwindcss/colors");
module.exports = {
  mode: "jit",
  darkMode: "class",
  purge: {
    enable: false,
    content: ["./src/**/*.vue"],
  },
  corePlugins: [
    process.env.UNI_PLATFORM === "h5" ? "preflight" : "container",
    "container",
    "alignContent",
    "alignItems",
    "backgroundColor",
    "backgroundPosition",
    "backgroundRepeat",
    "backgroundSize",
    "backgroundImage",
    "backgroundOpacity",
    "borderColor",
    "borderRadius",
    "borderStyle",
    "borderWidth",
    "boxSizing",
    //"boxShadow",
    "clear",
    "cursor",
    "display",
    // "divideWidth",
    "fill",
    "flex",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "fontSize",
    "fontWeight",
    "gradientColorStops",
    "height",
    "inset",
    "justifyItems",
    "justifyContent",
    "justifySelf",
    "lineHeight",
    "margin",
    "maxHeight",
    "maxWidth",
    "minHeight",
    "minWidth",
    "objectFit",
    "objectPosition",
    "opacity",
    "outline",
    "overflow",
    "pointerEvents",
    "position",
    "padding",
    "placeholderColor",
    "placeholderOpacity",
    "rotate",
    "ringColor",
    "ringOpacity",
    "ringWidth",
    "ringOffsetColor",
    "ringOffsetWidth",
    "scale",
    "tableLayout",
    "textAlign",
    "textColor",
    "textDecoration",
    "textOverflow",
    "textTransform",
    "transform",
    "transformOrigin",
    "transitionDelay",
    "transitionDuration",
    "transitionProperty",
    "transitionTimingFunction",
    "translate",
    "userSelect",
    "verticalAlign",
    "visibility",
    "whitespace",
    "width",
    "wordBreak",
    "zIndex",
  ],
  variants: {
    accessibility: [],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ["dark", "active", "disabled"],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: [],
    cursor: [],
    display: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: [],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: ["disabled"],
    order: [],
    outline: [],
    overflow: [],
    padding: [],
    placeholderColor: [],
    pointerEvents: [],
    position: [],
    resize: [],
    rotate: ["active"],
    scale: ["active"],
    stroke: [],
    tableLayout: [],
    textAlign: [],
    textColor: ["dark", "active"],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: ["active"],
  },
  theme: {
    screens: {
      sm: "640px",
      // => @media (min-width: 640px) { ... }
      md: "768px",
      // => @media (min-width: 768px) { ... }
      lg: "1024px",
      // => @media (min-width: 1024px) { ... }
      xl: "1280px",
    },
    spacing:
      process.env.UNI_PLATFORM !== "h5"
        ? {
            0: "0rpx",
            px: "2rpx",
            1: "8rpx",
            2: "16rpx",
            3: "24rpx",
            4: "32rpx",
            5: "40rpx",
            6: "48rpx",
            7: "56rpx",
            8: "64rpx",
            9: "72rpx",
            10: "80rpx",
            11: "84rpx",
            12: "96rpx",
            14: "112rpx",
            16: "128rpx",
            20: "160rpx",
            24: "192rpx",
            26: "208rpx",
            28: "224rpx",
            32: "256rpx",
            36: "288rpx",
            40: "320rpx",
            44: "352rpx",
            48: "384rpx",
            52: "416rpx",
            56: "448rpx",
            60: "480rpx",
            62: "496rpx",
            64: "512rpx",
            72: "576rpx",
            76: "608rpx",
            80: "640rpx",
            86: "688rpx",
            88: "704rpx",
            96: "768rpx",
          }
        : {
            0: "0px",
            px: "1px",
            1: "4px",
            2: "8px",
            3: "12px",
            4: "16px",
            5: "20px",
            6: "24px",
            7: "28px",
            8: "32px",
            9: "36px",
            10: "40px",
            11: "44px",
            12: "48px",
            14: "56px",
            16: "64px",
            20: "80px",
            24: "96px",
            28: "112px",
            32: "128px",
            36: "144px",
            40: "160px",
            44: "176px",
            48: "192px",
            52: "208px",
            56: "224px",
            60: "240px",
            64: "256px",
            72: "288px",
            75: "304px",
            80: "320px",
            86: "344px",
            88: "352px",
            96: "384px",
          },
    fontSize:
      process.env.UNI_PLATFORM !== "h5"
        ? {
            xxs: ["16rpx", { lineHeight: "20rpx" }],
            xs: ["24rpx", { lineHeight: "32rpx" }],
            sm: ["28rpx", { lineHeight: "40rpx" }],
            base: ["32rpx", { lineHeight: "48rpx" }],
            lg: ["36rpx", { lineHeight: "56rpx" }],
            xl: ["40rpx", { lineHeight: "56rpx" }],
            "2xl": ["48rpx", { lineHeight: "64rpx" }],
            "3xl": ["60rpx", { lineHeight: "72rpx" }],
            "4xl": ["72rpx", { lineHeight: "80rpx" }],
            "5xl": ["96rpx", { lineHeight: "1" }],
            "6xl": ["120rpx", { lineHeight: "1" }],
            "7xl": ["144rpx", { lineHeight: "1" }],
            "8xl": ["192rpx", { lineHeight: "1" }],
            "9xl": ["288rpx", { lineHeight: "1" }],
          }
        : {
            xxs: ["8px", { lineHeight: "10px" }],
            xs: ["12px", { lineHeight: "16px" }],
            sm: ["14px", { lineHeight: "20px" }],
            base: ["16px", { lineHeight: "24px" }],
            lg: ["18px", { lineHeight: "28px" }],
            xl: ["20px", { lineHeight: "28px" }],
            "2xl": ["24px", { lineHeight: "32px" }],
            "3xl": ["30px", { lineHeight: "36px" }],
            "4xl": ["36px", { lineHeight: "40px" }],
            "5xl": ["96rpx", { lineHeight: "1" }],
            "6xl": ["60px", { lineHeight: "1" }],
            "7xl": ["72px", { lineHeight: "1" }],
            "8xl": ["96px", { lineHeight: "1" }],
            "9xl": ["144px", { lineHeight: "1" }],
          },
    minHeight: {
      0: "0px",
      full: "100%",
      screen: "100vh",
    },
    outline: {
      none: ["4rpx solid transparent", "4rpx"],
      white: ["4rpx dotted white", "4rpx"],
      black: ["4rpx dotted black", "4rpx"],
    },
    extend: {
      colors: {
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        light: "var(--color-light)",
        // Build your palette here
        // red: {
        //   ...colors.red,
        //   default: "#D23B39",
        // },
        teal: colors.teal,
        orange: colors.orange,
        lime: colors.lime,
        rose: colors.rose,
      },
      minWidth: {
        "26": "208rpx",
      },
    },
  },
  plugins: [
    plugin(function({ addComponents }) {
      const buttons = {
        ".shadow": {
          boxShadow:
            "0 2rpx 6rpx 0 rgba(0, 0, 0, 0.1), 0 2rpx 4rpx 0 rgba(0, 0, 0, 0.06)",
        },
        ".shadow-white": {
          boxShadow: "8rpx 8rpx 8rpx 4rpx rgba(255, 255, 255, 0.1)",
        },
        ".shadow-lg": {
          boxShadow:
            "0 20rpx 30rpx -6rpx rgba(0, 0, 0, 0.1), 0 8rpx 12rpx -4rpx rgba(0, 0, 0, 0.05)",
        },
        ".text-shadow": {
          textShadow:
            "0px 0px 1px rgb(0 0 0 / 20%), 0px 0px 1px rgb(1 0 5 / 10%)",
        },
        ".text-shadow-sm": {
          textShadow: "1px 1px 3px rgb(36 37 47 / 25%)",
        },
        ".text-shadow-md": {
          textShadow:
            "0px 1px 2px rgb(30 29 39 / 19%), 1px 2px 4px rgb(54 64 147 / 18%)",
        },
        ".text-shadow-lg": {
          textShadow:
            "3px 3px 6px rgb(0 0 0 / 26%), 0 0 5px rgb(15 3 86 / 22%)",
        },
        ".text-shadow-xl": {
          textShadow:
            "1px 1px 3px rgb(0 0 0 / 29%), 2px 4px 7px rgb(73 64 125 / 35%)",
        },
        ".text-shadow-none": {
          textShadow: "none",
        },
      };

      addComponents(buttons);
    }),
  ],
};
